### ISSUE TITLE
FileNotFoundError while running

### ISSUE THREAD

**Issue by aditya187** [duo-labs/cloudtracker#23]
Getting following error while running "python cloudtracker.py --account demo --list users" command.

FileNotFoundError: [Errno 2] No such file or directory: 'account-data/demo-iam.json'

I have double checked and the demo-iam.json file exists under account-data. Can you please comment/check?

**Comment by 0xdabbad00** [comment]
Are you running on a linux based system?  The direction of the slash could be a problem.  You also want to ensure that the `account-data` directory exists in the same directory as the `cloudtracker.py` file.

**Comment by aditya187** [comment]
Thanks! It turned out to be a typo in the end, I had "demo-iam" in my config file, as compared to the correct "demo_iam". :)
