### ISSUE TITLE
Usage of --start option

### ISSUE THREAD

**Issue by z0ph** [duo-labs/cloudtracker#48]
Hey Scott,

Thanks for the amazing work, as usual.

Do you confirm that if I'm using : 
`cloudtracker --account myaccount --user myuser --show-used --start 2019-04-25`

The `--start` option is not used?

I was trying to identify the last used actions on a specific user after a specific date. (forensic, and least privilege building for a new policy)

Thanks,

**Comment by 0xdabbad00** [comment]
It should be used.  You can see here: https://github.com/duo-labs/cloudtracker/blob/master/cloudtracker/datasources/athena.py#L140

The `start` value makes it's way to that function, though I don't actually use the day.

**Comment by z0ph** [comment]
Do you mean that the whole month is used? so for me `04` last month/current month.

It will make sense as when using the current day (25), the actions used are very large...

**Comment by 0xdabbad00** [comment]
It basically chops off the day from the date, so `2019-04-25` should end up being the same as `2019-04`, so it should show everything in the past 25 days.

**Comment by z0ph** [comment]
Ok thanks!

**Comment by 0xdabbad00** [comment]
Closing as having been resolved. I should better clarify what data actually gets used though.
