### ISSUE TITLE
Create multiple partitions in a single call

### ISSUE THREAD

**Issue by 0xdabbad00** [duo-labs/cloudtracker#49]
From ajkerrigan on og-aws, he mentioned that that you can use "`add if not exists` and then add all partitions in a single query. I’m not sure where it tops out, but I’ve been able to conditionally add 365 partitions in a single call. ... That single call ended up taking ~15 seconds ... Combine it with dateutil’s rrule and `if not exists` to avoid double-adds, and it’s actually pretty sexy."

Partitions are added here: https://github.com/duo-labs/cloudtracker/blob/fd45948669b43a9accaf8aab052cdb83287d73e3/cloudtracker/datasources/athena.py#L300

**Comment by ajkerrigan-mdsol** [comment]
Thanks for the direct link! I'll have a look at that, and see about condensing those queries (without impacting the functionality).

**Comment by ajkerrigan-mdsol** [comment]
I read through this code, and I'm going to back away and touch nothing. You're already adding multiple partitions per call, just looks like you're batching by month. That seems perfectly reasonable given the partition volume. I don't want my first contribution to be blowing stuff up for no good reason, so I'll just say thanks for a nifty product!

**Comment by 0xdabbad00** [comment]
I think there are some improvements can be made based on your idea.  I'll keep this ticket open and look into it further at some point when I focus on this project again.  I've been told AWS is going to document CloudTrail better and I have some plans for leveraging AWS's Client Side Monitoring that will push me into focusing on this project again more.

**Comment by ajkerrigan-mdsol** [comment]
Ok perfect, sounds good. If you want a hand (or at least a sounding board for ideas) feel free to hit me up here or on og-aws.

And in case it ends up being relevant, I pushed up some local tweaks [here](https://github.com/ajkerrigan-mdsol/cloudtracker/tree/athena-partition-refactor). I don't think the changes make enough of a difference to warrant a merge as-is, but some of the tweaks might be useful elsewhere.

**Comment by 0xdabbad00** [comment]
I'm unfortunately not going to focus on any work in this project for creating Athena things, and should instead focus on creating Athena partitions in https://github.com/duo-labs/cloudtrail-partitioner
