### ISSUE TITLE
Incorrect partitions built for GovCloud

### ISSUE THREAD

**Issue by jmhale** [duo-labs/cloudtracker#50]
When trying to run cloudtracker against a AWS GovCloud account, no results are returned, because the partitions are being built against the list of Commercial regions, which it's getting from the `get_available_regions` call. https://github.com/duo-labs/cloudtracker/blob/master/cloudtracker/datasources/athena.py#L274

This is because the `partition_name` arg is omitted (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.get_available_regions)

Obviously, this is fine for most use cases, but it would nice if we could toggle a flag in config to get GovCloud-specific env data.

**Comment by 0xdabbad00** [comment]
Closing this as I'm going to focus on creating Athena tables in https://github.com/duo-labs/cloudtrail-partitioner
