### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by ayysasha** [duo-labs/cloudtracker#64]
Hello All,

Even after providing the permissions listed to the service account this will be running with, I am running into AWS permissions errors, my latest being one around glue permissions.

Is there any full list of permissions that this requires, as in my environment giving an resource wildcard is not possible.

I see that under data/aws_api_list and Cloudtrail_supported_actions there is a large list of actions, but I am assuming that is just an exhaustive list and not one of required permissions for the running user.

Thanks!

**Comment by 0xdabbad00** [comment]
From https://github.com/duo-labs/cloudtracker#step-4-run-cloudtracker 
```
You will need the privilege arn:aws:iam::aws:policy/AmazonAthenaFullAccess and also s3:GetObject and s3:ListBucket for the S3 bucket containing the CloudTrail logs.
```

I have not dwindled down the permissions further (which is awkward I realize for a tool whose purpose is to help with least privileges).  PRs for this are welcome.

**Comment by ayysasha** [comment]
After about a day I dwindled it down without using a single wildcard. Will PR when I make sure its 100% working, running into additional rate limit issues right now. Athena requires strange Glue permissions as well which is why I was getting errors when only granting full Athena access to specific resources.
