### ISSUE TITLE
Document which elasticsearch versions are supported

### ISSUE THREAD

**Issue by danielpops** [duo-labs/cloudtracker#7]
The query language semantics change between the major versions of elasticsearch. Seems that the version I'm testing against is not compatible with cloudtracker. Seems that elasticsearch 2.0 is a minimum requirement, based on the error I observed. Is that correct? (or maybe it's 6.0, based on requirements.txt contents). It would be helpful to include a "compatibility matrix" in the README that shows what versions are known to work and when you're in uncharted territories.

Bonus points for automagically supporting all major versions :)

**Comment by 0xdabbad00** [comment]
Requirements added in https://github.com/duo-labs/cloudtracker/commit/228433380dc348f6e118737f60b6e9f11c0d4f70

I've only ever tested with ElasticSearch 6.1.1

I'll leave it up to you to hopefully get ES 1.x working :)
