### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Almenon** [duo-labs/cloudtracker#84]
Cloudtracker looked like a really cool tool, so I tried it out, but ran into a performance issue. On a account with a lot of users cloudtracker is quite slow. It looks like it's just partitioning by date, not user, so searching for a single user searches _all_ users. At that point the performance of the python code doesn't matter because the Athena query alone takes some time. Is there a reason why it's not partitioning by user?

**Comment by 0xdabbad00** [comment]
Cloudtrail logs are partitioned by date, so this uses what Cloudtrail offers.

**Comment by Almenon** [comment]
Makes sense, thanks for the quick response
